server:
  build: .
  volumes:
    - ./conf.js:/app/conf.js
    - ./lib:/app/lib
  links:
    - mongodb
  command: []
  restart: always

mongodb:
  image: mongo:latest
  volumes_from:
    - mongodb-data
  command: mongod --smallfiles

mongodb-data:
  image: mongo:latest
  volumes:
    - /data/db
  command: "true"
